- name: UID test
  hosts: ism
  collections:
    - inspur.sm
  connection: local
  gather_facts: no
  vars:
    ism:
      host: "{{ ansible_ssh_host }}"
      username: "{{ username }}"
      password: "{{ password }}"

  tasks:

  - name: "Set uid"
    edit_uid:
      led: "on"
      time: 10
      provider: "{{ ism }}"

  - name: "Set uid"
    edit_uid:
      led: "off"
      provider: "{{ ism }}"